version: "3.8"

services:
  toolbox:
    image: flemay/musketeers
    working_dir: /app
    volumes:
      - ${PWD}:/app

  terraform:
    image: hashicorp/terraform:0.13.0
    working_dir: /terraform
    volumes:
      - ${PWD}/terraform:/terraform
      - ${HOME}/.aws:/root/.aws
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - TF_IN_AUTOMATION=yes
  
  jq:
    image: stedolan/jq
    working_dir: /app
    volumes:
      - ${PWD}:/app